(() => {
  const root=document.querySelector('#listeningView');
  const official='https://ielts.org/take-a-test/preparation-resources/sample-test-questions/academic-test';
  const samples=[
    {title:'Café Order',level:'A2 · Everyday English',text:'Customer: Could I get a latte with oat milk, please? Barista: Of course. Would you like a small or a large one? Customer: A small one, please. And no sugar. Barista: That will be four pounds. Customer: Can I pay by card? Barista: Yes, you can.',translation:'顾客想要一小杯燕麦奶拿铁，不加糖，价格四英镑，并询问能否刷卡。',questions:[['What drink does the customer choose?',['An oat-milk latte','An iced Americano','A hot chocolate'],0,'The customer says “latte with oat milk”.'],['What size does the customer choose?',['A large one','A small one','The size is not stated'],1,'The customer clearly says “A small one”.'],['How much does it cost?',['Two pounds','Three pounds','Four pounds'],2,'The barista says “four pounds”.']]},
    {title:'Rescheduling a Meeting',level:'B1 · Workplace English',text:'Jamie: Could we move our meeting from Thursday to Friday? Alex: Friday morning works for me. How about ten? Jamie: I have a call at ten. Could we meet at eleven instead? Alex: Certainly. Shall we use room three? Jamie: Room three is booked. Let us meet in room five. Alex: Great. I will send an updated invitation.',translation:'原定周四的会议改到周五上午十一点。三号会议室已被预订，因此改用五号会议室。',questions:[['Which day is the meeting moved to?',['Thursday','Friday','Monday'],1,'They agree to move it to Friday.'],['What time is finally agreed?',['Ten o’clock','One o’clock','Eleven o’clock'],2,'Ten is busy, so they choose eleven.'],['Which room will they use?',['Room five','Room three','Room one'],0,'Room three is booked, so they choose room five.']]},
    {title:'Library Announcement',level:'B1–B2 · Campus English',text:'Welcome to the library. During the exam period, the main reading room will stay open until midnight from Monday to Friday. On weekends, it will close at eight in the evening. You may borrow up to six books at a time. Study rooms must be booked online at least one day in advance. Please leave food outside, but water bottles are allowed.',translation:'考试期间主阅览室工作日开放至午夜，周末晚上八点关闭。最多借六本书，研讨室需至少提前一天在线预约。不能带食物，但可以带水。',questions:[['When does the library close at weekends?',['At midnight','At six p.m.','At eight p.m.'],2,'The weekend closing time is eight in the evening.'],['How many books may you borrow?',['Four','Six','Eight'],1,'The notice says “up to six books”.'],['How must study rooms be booked?',['In person on the same day','Online at least one day in advance','No booking is required'],1,'They must be booked online in advance.']]}
  ];
  samples.push(...(window.extraListeningLessons||[]));
  const storageKey='linguaflow.listening.v1';let records={};try{records=JSON.parse(localStorage.getItem(storageKey))||{}}catch{}
  let index=0,utterance=null;const $=s=>root.querySelector(s);
  root.innerHTML=`<div class="library-head"><div><div class="eyebrow">LISTENING LAB</div><h2>听力训练</h2></div></div><section class="panel"><h3>官方考试材料</h3><p>IELTS 官方公开样题：含录音、题目、标准答案及听力原文。官方未标明为历年真题，因此这里按“官方样题”收录。</p><div class="v-actions"><a href="${official}" target="_blank" rel="noopener">打开官方听力样题与答题入口 ↗</a></div><details><summary>查看官方答案与听力原文</summary><p>在官方页面的 Listening 栏选择题型，可打开对应的 Answer Key 和 Recording Transcript。以下是已核对的原文入口：</p><ul><li><a href="https://cdn.ielts.org/computer-delivered-sample-tests-listening/ielts-listening-computer-delivered-multiple-choice-one-answer-transcript.pdf" target="_blank" rel="noopener">单选题：伦敦东区研究 · 官方原文 PDF</a></li><li><a href="https://cdn.ielts.org/computer-delivered-sample-tests-listening/ielts-listening-computer-delivered-multiple-choice-more-than-one-answer-transcript.pdf" target="_blank" rel="noopener">多选题：图书馆指南 · 官方原文 PDF</a></li><li><a href="https://cdn.ielts.org/computer-delivered-sample-tests-listening/ielts-listening-computer-delivered-plan-map-diagram-labelling-transcript.pdf" target="_blank" rel="noopener">地图题：小镇导览 · 官方原文 PDF</a></li></ul></details></section><section class="panel" style="margin-top:20px"><h3>站内听力练习</h3><p class="v-status">原创练习，使用设备英语语音朗读；不是考试原声。提交答案后显示完整原文和解析。</p><div class="v-controls"><label>选择内容<select id="listenLesson"></select></label><label>播放速度<select id="listenRate"><option value="0.8">慢速</option><option value="1" selected>正常</option><option value="1.15">稍快</option></select></label></div><div class="v-actions"><button id="realPlay">▶ 播放听力</button><button id="realStop">■ 停止</button></div><p id="realAudioStatus" role="status">点击播放后开始听音。</p><form id="listenForm"><div id="listenQuestions"></div><button class="next-btn" type="submit">提交答案并查看原文</button></form><div id="listenResult" aria-live="polite"></div></section>`;
  const filterLabel=document.createElement('label');filterLabel.textContent='难度筛选';const filter=document.createElement('select');filter.id='listenDifficulty';['全部','A2','B1','B2'].forEach(x=>filter.add(new Option(x,x)));filterLabel.append(filter);$('.v-controls').prepend(filterLabel);
  const count=document.createElement('p');count.className='v-status';count.id='listenBankCount';$('.v-controls').before(count);
  const next=document.createElement('button');next.textContent='下一套练习 →';next.type='button';next.id='listenNext';next.className='next-btn';$('#listenResult').after(next);
  next.style.marginTop='20px';
  function fillLessons(){const select=$('#listenLesson');select.replaceChildren();samples.forEach((s,i)=>{if(filter.value==='全部'||s.level.split(' · ')[0].includes(filter.value))select.add(new Option(s.title+' · '+s.level,i))});if(![...select.options].some(o=>Number(o.value)===index))index=Number(select.options[0].value);select.value=String(index);count.textContent=`共 ${samples.length} 套 · ${samples.reduce((n,s)=>n+s.questions.length,0)} 道题 · 当前分类 ${select.options.length} 套`;}
  filter.onchange=()=>{fillLessons();render()};next.onclick=()=>{const select=$('#listenLesson');select.selectedIndex=(select.selectedIndex+1)%select.options.length;index=Number(select.value);render();select.focus()};fillLessons();
  const style=document.createElement('style');style.textContent='#listeningView p{line-height:1.8}#listeningView a{color:#076962}#listeningView fieldset{border:1px solid #e5ebef;border-radius:12px;margin:18px 0;padding:16px}#listeningView fieldset label{display:block;padding:10px;cursor:pointer}#listeningView summary{cursor:pointer;padding:14px 0;font-weight:700}#listeningView select{max-width:100%}';document.head.append(style);
  function stop(){if(window.speechSynthesis)speechSynthesis.cancel();utterance=null;$('#realAudioStatus').textContent='已停止播放';}
  function result(rec){const box=$('#listenResult');box.replaceChildren();if(!rec)return;const s=samples[index],score=s.questions.filter((q,i)=>rec.answers[i]===q[2]).length;const heading=document.createElement('h3');heading.textContent=`答对 ${score} / ${s.questions.length} 题`;box.append(heading);
    s.questions.forEach((q,i)=>{const p=document.createElement('p');p.textContent=`${i+1}. ${rec.answers[i]===q[2]?'正确':'错误'} · 你的答案：${q[1][rec.answers[i]]}；正确答案：${q[1][q[2]]}。${q[3]}`;box.append(p)});
    const details=document.createElement('details');details.open=true;const summary=document.createElement('summary');summary.textContent='听力原文与中文概要';const transcript=document.createElement('p');transcript.lang='en';transcript.textContent=s.text;const translation=document.createElement('p');translation.textContent=s.translation;details.append(summary,transcript,translation);box.append(details);
  }
  function render(){stop();$('#listenQuestions').replaceChildren();const rec=records[index];samples[index].questions.forEach((q,i)=>{const field=document.createElement('fieldset');const legend=document.createElement('legend');legend.textContent=`${i+1}. ${q[0]}`;field.append(legend);q[1].forEach((answer,j)=>{const label=document.createElement('label'),radio=document.createElement('input');radio.type='radio';radio.name='q'+i;radio.value=j;radio.required=true;radio.checked=rec?.answers?.[i]===j;label.append(radio,document.createTextNode(' '+answer));field.append(label)});$('#listenQuestions').append(field)});result(rec);$('#realAudioStatus').textContent='点击播放后开始听音。';}
  $('#listenLesson').onchange=e=>{index=Number(e.target.value);render()};$('#realStop').onclick=stop;
  $('#realPlay').onclick=()=>{if(!window.speechSynthesis){$('#realAudioStatus').textContent='此浏览器不支持语音，请使用上方官方听力入口。';return;}stop();const u=new SpeechSynthesisUtterance(samples[index].text);utterance=u;u.lang='en-GB';u.rate=Number($('#listenRate').value);u.onstart=()=>{if(utterance===u)$('#realAudioStatus').textContent='正在播放…'};u.onend=()=>{if(utterance===u)$('#realAudioStatus').textContent='播放完成，可重听或提交答案。'};u.onerror=()=>{if(utterance===u)$('#realAudioStatus').textContent='播放失败，请检查设备英语语音支持，或打开官方练习。'};$('#realAudioStatus').textContent='正在准备英语语音…';speechSynthesis.speak(u)};
  $('#listenForm').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);const answers=samples[index].questions.map((_,i)=>Number(data.get('q'+i)));records[index]={answers,at:Date.now()};result(records[index]);try{localStorage.setItem(storageKey,JSON.stringify(records));window.dispatchEvent(new Event('learning-progress-updated'))}catch{const p=document.createElement('p');p.textContent='当前浏览器不允许保存，答题结果仅在本页保留。';$('#listenResult').append(p)}};
  const officialPanel=root.querySelector('section');
  officialPanel.style.marginTop='20px';
  root.append(officialPanel);
  const observer=new MutationObserver(()=>{if(!root.classList.contains('active'))stop()});observer.observe(root,{attributes:true,attributeFilter:['class']});render();
})();
